config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit, :new, :create]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save :formalize_user
  before_create :create_activation_digest


  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                          format: { with: VALID_EMAIL_REGEX },
                          uniqueness: { case_sensitive: false }

  # presence of password and password_confirmation is validates through bcrypt
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  #returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    #create token
    SecureRandom.urlsafe_base64
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def remember
    # first create a token
    self.remember_token = User.new_token
    # and we digest that token and store it in the db for comparison
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, :nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    self.update_attributes(activated: true,
                           activated_at: Time.now)
  end

  def update_activation_digest
    self.activation_token = User.new_token
    self.update_attribute(:activation_digest, User.digest(activation_token))
  end

  private

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def formalize_user
    self.email.downcase!
    self.name = self.name.titleize
  end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated && user.authenticated?('activation', params[:id])
      user.activate
      log_in user
      flash[:success] = "Hello #{user.name}"
      redirect_to user
    else
      flash[:danger] = 'Activation invalid'
      redirect_to root_url
    end
  end

  def new
  end

  def create
    @user = User.find_by(email: params[:account_activations][:email])
    if @user && !@user.activated
      @user.update_activation_digest
      @user.send_activation_email
      flash[:success] = "Your email should be there soon."
    elsif user.activated
      flash[:Warning] = "This account has already been activated."
    else
      flash[:danger] = "Account not found."
    end
    redirect_to login_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    # if user exists && password correct
    if @user && @user.authenticate(params[:session][:password])
      #SessionsHelper
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to @user
    else
      flash.now[:danger] = "Invalid Username / Password Combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def contact
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:warning] = "Account not activated, please check email."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile successfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :email_confirmation,
                                 :password, :password_confirmation)
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = "")
    base_title = "The Clubhouse"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def gravatar_url(email, size = '64')
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end

end

app/helpers/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember #generates the token, stores digest on db
    cookies.permanent.signed[:user_id] = user.id # permanently store and encrypt user id within cookie
    cookies.permanent.signed[:remember_token] = user.remember_token # permanently store and encrypt the remember token within cookie
  end

  def current_user
    # only hits the db once
    ## find_by method returns nil if id not found
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?('remember', cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user) ##pulls in user model, puts it in user var
    user.remember # remember method in the user model
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent.signed[:remember_token] = user.remember_token
  end
  # has only to do with the session part of the user
  # requires a forget method in model to handle the attribute
  def forget(user)
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    image_tag gravatar_url(user.email)
  end

end

app/views/account_activations/new.html.erb
<% provide(:title, "Confirmation Email") %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for :account_activations, url: account_activations_path do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default ">
  <p class="text-center text-muted">
    The Clubhouse&reg; | Gregory Bastianelli
  </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo-blue.png", class: "navbar-brand"), root_url %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", '#' %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(@current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Register", new_user_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_html_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_rails_tags.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- application_helper.rb -->
    <title><%= full_title(yield(:title))%></title>
    <%= render 'layouts/html_shim' %>
    <%= render 'layouts/rails_tags' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{type}") %>
      <% end %>

      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>


    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="text-danger"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Project 2: Members Only!</h1>
    <p class="">
      In this project, you’ll be building an exclusive clubhouse where your members can write embarrassing posts about non-members. Inside the clubhouse, members can see who the author of a post is but, outside, they can only see the story and wonder who wrote it.

    This will be a chance for you to “roll your own” authentication system, very similar to how you did in the tutorial. As usual, we will be focusing on data and function, not style. If you want to add your own stylistic flourishes, consider it extra credit.

    It’s easy to feel a bit overwhelmed by building your own authentication. That’s because there are several moving parts – the session controller/form, hanging onto and refreshing the remember token when necessary, and using that token to check up on the current user. It may help if you write out the steps as you understand them prior to getting started, so you know what you’re shaky on and will need to pay attention to.
    </p>

    <h3>Assignment</h3>

    <p class="">
      The projects will be less and less explicit about how to achieve their goals, since we expect you to build on your previous knowledge. If you don’t know how to do something, feel free to check back in previous lessons or projects or Google the correct way to implement it (though be careful, because that may take you deeper down the road than we intended). The Ruby on Rails Tutorial will be a good reference.

    Up until now, we’ve been treating the “password” field of user submissions pretty cavalierly… it’s mostly been an afterthought included for the sake of completeness. We certainly haven’t been storing them properly or encrypting them, which we should. So wipe all that stuff from your memory because now you’ve got the tools to properly encrypt user passwords and we’ll be doing it from now on. Actually, you’ve had the tools since back when you did chapter 6 of the Ruby on Rails Tutorial.

    If you’d like to challenge yourself, don’t even follow the steps below, just go ahead and build the app!
    </p>
    <Br />
    <%= link_to "See Project", "https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication?ref=lnav", class: 'btn btn-primary btn-block' %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>


<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1>Contact</h1>
      <p class="lead">
        Practicing Mailers and Forms.
      </p>
    </div>
    <p class="">
       I plan to make a basic form for users to contact the admin (me) and complain about the site.
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home')%>


<div class="jumbotron text-center">
  <h1>Welcome to the <em>Clubhouse</em>!</h1>
  <p style="width: 70%; margin: 15px auto;">A site where users can post secrets about non-users and they will never know who wrote them! (unless the sign up as well).</p>
  <%= link_to 'Register today!', new_user_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= render 'shared/error_messages' %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_tag gravatar_url(user.email, 32) %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<% provide(:btn_text, 'Save Changes') %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1>Edit Profile</h1>
    <%= render 'form' %>
    <div class="form-group">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">Change Gravatar</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>All Users</h1>
    <ul class="users">
      <%= render @users %>
    </ul>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<% provide(:btn_text, 'Register Account') %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1>Sign up!</h1>
    <%= render 'form' %>
    
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="pull-left">
      <%= image_tag gravatar_url(@user.email, 64), alt: "", class: 'profile-pic' %>
    </div>
    <h1><%= @user.name %></h1>
    <p class="text-muted">
      <%= @user.email %>
    </p>
  </div>
</div>